CREATE DATABASE badalyan;
CREATE ROLE badalyan WITH LOGIN ENCRYPTED PASSWORD 'b72e3ve';
ALTER ROLE badalyan SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE vlasenko;
CREATE ROLE vlasenko WITH LOGIN ENCRYPTED PASSWORD '78v2s3f';
ALTER ROLE vlasenko SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE gritsenko;
CREATE ROLE gritsenko WITH LOGIN ENCRYPTED PASSWORD '23d4hj8';
ALTER ROLE gritsenko SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE gusev;
CREATE ROLE gusev WITH LOGIN ENCRYPTED PASSWORD 'gu78s2q';
ALTER ROLE gusev SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE zhigalov;
CREATE ROLE zhigalov WITH LOGIN ENCRYPTED PASSWORD '50s7h8w';
ALTER ROLE zhigalov SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE zemskova;
CREATE ROLE zemskova WITH LOGIN ENCRYPTED PASSWORD 'z78w20a';
ALTER ROLE zemskova SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE kalinin;
CREATE ROLE kalinin WITH LOGIN ENCRYPTED PASSWORD '43sk2e7';
ALTER ROLE kalinin SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE kaulin;
CREATE ROLE kaulin WITH LOGIN ENCRYPTED PASSWORD 'k45d2ul';
ALTER ROLE kaulin SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE koval;
CREATE ROLE koval WITH LOGIN ENCRYPTED PASSWORD 'k7o2a47';
ALTER ROLE koval SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE krivtsov;
CREATE ROLE krivtsov WITH LOGIN ENCRYPTED PASSWORD '20r7o3q';
ALTER ROLE krivtsov SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE lozhkin;
CREATE ROLE lozhkin WITH LOGIN ENCRYPTED PASSWORD '1o6a0w7';
ALTER ROLE lozhkin SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE makarenkov;
CREATE ROLE makarenkov WITH LOGIN ENCRYPTED PASSWORD '83c5t1q';
ALTER ROLE makarenkov SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE marchenko;
CREATE ROLE marchenko WITH LOGIN ENCRYPTED PASSWORD 'df2y2q6';
ALTER ROLE marchenko SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE ponomarev;
CREATE ROLE ponomarev WITH LOGIN ENCRYPTED PASSWORD 'po0z8ql';
ALTER ROLE ponomarev SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE rychkin;
CREATE ROLE rychkin WITH LOGIN ENCRYPTED PASSWORD '23w1b8d';
ALTER ROLE rychkin SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE ryabov;
CREATE ROLE ryabov WITH LOGIN ENCRYPTED PASSWORD '19x8t2a';
ALTER ROLE ryabov SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE sumenkov;
CREATE ROLE sumenkov WITH LOGIN ENCRYPTED PASSWORD '9s3g2r5';
ALTER ROLE sumenkov SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE fedotkin;
CREATE ROLE fedotkin WITH LOGIN ENCRYPTED PASSWORD 'fl25w3f';
ALTER ROLE fedotkin SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE sharifova;
CREATE ROLE sharifova WITH LOGIN ENCRYPTED PASSWORD 'vl5d4ty';
ALTER ROLE sharifova SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE shirikov;
CREATE ROLE shirikov WITH LOGIN ENCRYPTED PASSWORD 'sh2t5e3';
ALTER ROLE shirikov SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE shlapakov;
CREATE ROLE shlapakov WITH LOGIN ENCRYPTED PASSWORD 'v2r6o2f';
ALTER ROLE shlapakov SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE shchukinl;
CREATE ROLE shchukinl WITH LOGIN ENCRYPTED PASSWORD 'u2e3ch8';
ALTER ROLE shchukinl SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;
