CREATE DATABASE antyukhova;
CREATE ROLE àntyukhova WITH LOGIN ENCRYPTED PASSWORD 'a1nty23';
ALTER ROLE àntyukhova SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;


CREATE DATABASE gapchenko;
CREATE ROLE gapchenko WITH LOGIN ENCRYPTED PASSWORD 'g3ap8ch';
ALTER ROLE gapchenko SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE dyadyun;
CREATE ROLE dyadyun WITH LOGIN ENCRYPTED PASSWORD 'u5nc32e';
ALTER ROLE dyadyun SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE eliseeva;
CREATE ROLE eliseeva WITH LOGIN ENCRYPTED PASSWORD 'el4is8v';
ALTER ROLE eliseeva SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE zavalnyuk;
CREATE ROLE zavalnyuk WITH LOGIN ENCRYPTED PASSWORD 'za43v7k';
ALTER ROLE zavalnyuk SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE ivanov;
CREATE ROLE ivanov WITH LOGIN ENCRYPTED PASSWORD 'i0va8n3v';
ALTER ROLE ivanov SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE kanziberov;
CREATE ROLE kanziberov WITH LOGIN ENCRYPTED PASSWORD 'k4nz5bv';
ALTER ROLE kanziberov SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE klemin;
CREATE ROLE klemin WITH LOGIN ENCRYPTED PASSWORD 'kl3m1n7';
ALTER ROLE klemin SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE konkov;
CREATE ROLE konkov WITH LOGIN ENCRYPTED PASSWORD '5kat7s0';
ALTER ROLE konkov SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE kryukov;
CREATE ROLE kryukov WITH LOGIN ENCRYPTED PASSWORD 'k1y4k0v';
ALTER ROLE kryukov SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE loban;
CREATE ROLE loban WITH LOGIN ENCRYPTED PASSWORD 'l0b2an8';
ALTER ROLE loban SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE makeev;
CREATE ROLE makeev WITH LOGIN ENCRYPTED PASSWORD 'm0k6ev4';
ALTER ROLE makeev SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE malofeev;
CREATE ROLE malofeev WITH LOGIN ENCRYPTED PASSWORD '12lof5v';
ALTER ROLE malofeev SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE milovanova;
CREATE ROLE milovanova WITH LOGIN ENCRYPTED PASSWORD '5m1a4o0';
ALTER ROLE milovanova SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE novikova;
CREATE ROLE novikova WITH LOGIN ENCRYPTED PASSWORD '89nv2kv';
ALTER ROLE novikova SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE pavlov;
CREATE ROLE pavlov WITH LOGIN ENCRYPTED PASSWORD '73pa1v7';
ALTER ROLE pavlov SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE ponomarev_ivan;
CREATE ROLE ponomarev_ivan WITH LOGIN ENCRYPTED PASSWORD 'p8o1m5r';
ALTER ROLE ponomarev_ivan SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE smirnova;
CREATE ROLE smirnova WITH LOGIN ENCRYPTED PASSWORD '4sm6i9a';
ALTER ROLE smirnova SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE smolchenkov;
CREATE ROLE smolchenkov WITH LOGIN ENCRYPTED PASSWORD 's76o9n3';
ALTER ROLE smolchenkov SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE torosyan;
CREATE ROLE torosyan WITH LOGIN ENCRYPTED PASSWORD '45t6r0a';
ALTER ROLE torosyan SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE horkin;
CREATE ROLE horkin WITH LOGIN ENCRYPTED PASSWORD 'h0r47r7';
ALTER ROLE horkin SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE khustochka;
CREATE ROLE khustochka WITH LOGIN ENCRYPTED PASSWORD '12g5k3y';
ALTER ROLE khustochka SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE tsukanov;
CREATE ROLE tsukanov WITH LOGIN ENCRYPTED PASSWORD '8fk12s9';
ALTER ROLE tsukanov SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE cherepanov;
CREATE ROLE cherepanov WITH LOGIN ENCRYPTED PASSWORD '83d4l6m';
ALTER ROLE cherepanov SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE yakovlev;
CREATE ROLE yakovlev WITH LOGIN ENCRYPTED PASSWORD '86h3fd7';
ALTER ROLE yakovlev SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;

CREATE DATABASE yakunova;
CREATE ROLE yakunova WITH LOGIN ENCRYPTED PASSWORD '62np4d0';
ALTER ROLE yakunova SUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN REPLICATION BYPASSRLS;
